### ISSUE TITLE
ISA Context Problems

### ISSUE THREAD

**Issue by floWetzels** [nfdi4plants/arc-to-rocrate#1]
ISA json-context files from the isa-api have the following semantical problems for the conversion to RO-Crate

### Mapping leading to problems with RO-Crate
- Contexts overall do not fit to `RO-Crate` conventions, since all studies and assays (subfolders in an ARC) should be `sdo:Dataset`:
  >  Data Entities representing directories MUST be of "@type": "Dataset"
  
   see [RO-Crate specification](https://www.researchobject.org/ro-crate/1.1/data-entities.html).

### Mapping leading to illegal relationships
- `isa:Assay` mapped to `sdo:MedicalTest`, `isa:measurementType` mapped to `sdo:variableMeasured`, but the latter is not part of `sdo:MedicalTest`, even though such a relationship exists in the datamodel.
- `isa:characteristicCategories` mapped to `sdo:measuredProperty`, but the latter not part of `sdo:MedicalTest`.
- `isa:Study` mapped to `sdo:MedicalStudy`, `isa:studyDesignDescriptors` mapped to `sdo:trialDesign`, but the latter is not part of `sdo:MedicalStudy`.
- `isa:affiliations` of i`sa:Person` mapped to `sdo:affiliation` of `sdo:Person`, but types don't fit (Text vs Organization). Where does `isa:Organization` come from? Not part of the specification.

### Mapping of non-existent fields
- `Assay context` maps identifier, name, description, but they are not properties of `isa:Assay`.

### Mapping which doesn't fit semantically
- `isa:Sample` to `sdo:Product`
- `isa:Protocol` to `sdo:HowTo`
-  `isa:Comment` to `sdo:Comment` (they describe different things!).
- `isa:material` mapped to `sdo:participant`.

Thus, I suggest to write ARC/RO-Crate specific context files manually.

**Comment by HLWeil** [comment]
I think we can close this, having created our own profile in https://github.com/nfdi4plants/isa-ro-crate-profile? @floWetzels

**Comment by floWetzels** [comment]
This is no longer relevant for us, so I think you're right. But I guess this is still something to keep in mind to talk to some of the ISA people to? Not sure...
